from random import choice

books = [
    "Tome",
    "Volume",
    "Book",
    "Opus",
    "Treatise",
    "Ledger",
    "Paperback",
    "Handbook",
    "Scroll",
    "Dictionary",
    "Compendium",
    "Manuscript",
    "Manual",
    "Chronicle",
    "Folio",
    "Incunabulum",
    "Thesaurus",
    "Herbarium",
    "Saga",
    "Catalogue",
    "Cyclopaedia",
    "Testamentum",
    "Grimoire",
    "Liber",
    "Lesser Key",
    "Daemonarium",
    "Idiot's Guide",
]

schools = [
    "Power",
    "Might",
    "Mystery",
    "Befuddlement",
    "Ice Magic",
    "Magic",
    "Sorcery",
    "Hexes",
    "Charms",
    "Spells",
    "Damnation",
    "Wisdom",
    "Secrets",
    "Chaos",
    "Witchcraft",
    "Necromancy",
    "the Occult",
    "Enchantment",
    "Binding",
    "Incantation",
    "Esoterica",
    "the Eldritch",
    "the Dead",
    "the Karcist",
    "Summoning",
    "Angelology",
    "Transformation",
    "Witchery",
    "Wizzardry",
    "Poisons",
    "Alchemy",
    "Madjgycke",
    "Unholy Arts",
    "Fireballs for Dummies",
    "Lycanthropy",
    "Haruspicy",
    "Prophecy",
    "Discord",
    "Alectromancy",
    "Ceromancy",
    "Cleromancy",
    "Chronomancy",
    "Numerology",
    "Oneiromancy",
    "Tasseomancy",
    "Cartomancy",
    "Rhabdomancy",
    "Pyromancy",
    "Thaumaturgy",
    "Exorcism",
]

rare_schools = [
    "Inexplicable Woodcuts",
    "Doodles",
    "Erotic Vampire Fiction",
    "Postmodern Theory",
    "Some Harry Potter Bullshit",
    "Philology",
    "Horse Training",
    "Abyssal Sudoku",
    "Old Babylonian Crossword Puzzles",
    "Diophantane Approximation",
    "Card Tricks",
    "Flim-Flam",
    "Con Artistry",
    "Frauds and Swindles",
    "Rude Latin Poetry",
    "Awkwardly Out of Date Orientalism",
    "Mistranslated Egyptian Funerary Texts",
    "Malarky",
    "Gastromancy",
    "Illiberal Arts",
    "Most Wickedde Magicke",
    "Brainfuck",
    "Unusual Beasts",
    "the Wonders of the East",
    "Cryptography",
    "Fortran",
    "Slutty Magic",
    "Nonsense",
    "Old Languages",
    "Jargon",
    "Must",
    "Smells",
]


def random_spellbook():
    rare_book = not choice(range(10))
    if rare_book:
        return choice(books) + " of " + choice(rare_schools)
    else:
        return choice(books) + " of " + choice(schools)


if __name__ == "__main__":
    for _ in range(100):
        print(random_spellbook())
